# Generated by Django 4.2.17 on 2025-01-13 11:48

from django.db import migrations


def add_teams(apps, schema):
    model = apps.get_model('users', 'Team')
    teams = [
        model(name='Amigos', recruit=False),
        model(name='Coyote70', recruit=False),
        model(name='Krait', recruit=False),
        model(name='Saft9', recruit=False),
        model(name='Вежливые', recruit=False),
        model(name='Миражи', recruit=False),
        model(name='ST-5', recruit=False),
        model(name='Почетный член ТГ', recruit=False),
        model(name='Горячие головы', recruit=True),
        model(name='Виски 7', recruit=True),

    ]

    model.objects.bulk_create(teams)


def delete_teams(apps, schema):
    model = apps.get_model('users', 'Team')
    model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_teams, delete_teams)
    ]
