# Generated by Django 4.2.17 on 2025-02-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Если установлен, то пользователь забанен в боте и канале. Ему не будет доступна рассылка и функционал', verbose_name='Забанен'),
        ),
    ]
