# Generated by Django 4.2.17 on 2025-02-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_is_banned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Телеграм пользователь', 'verbose_name_plural': 'Телеграм пользователи'},
        ),
    ]
