# Generated by Django 4.2.17 on 2025-01-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='responsible_person',
            field=models.BooleanField(default=False, verbose_name='Является ответственным лицом'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Телеграм логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.team', verbose_name='Команда'),
        ),
    ]
