# Generated by Django 4.2.17 on 2025-02-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameeventnotification',
            name='allow_discussion',
            field=models.BooleanField(default=True, verbose_name='Уведомление с комментариями'),
        ),
        migrations.AddField(
            model_name='gameeventnotification',
            name='message_for',
            field=models.SmallIntegerField(choices=[(1, 'В бот'), (2, 'В канал')], default=2, verbose_name='Сообщение для'),
        ),
    ]
