# Generated by Django 4.2.17 on 2025-02-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_update_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='games',
            name='judas_commander',
        ),
        migrations.AddField(
            model_name='games',
            name='game_map',
            field=models.ImageField(blank=True, null=True, upload_to='images/game_map', verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='games',
            name='location_map',
            field=models.ImageField(blank=True, null=True, upload_to='images/location_map', verbose_name='Карта проезда'),
        ),
        migrations.AddField(
            model_name='games',
            name='toyan_commander',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Командующий Тояном'),
        ),
    ]
