# Generated by Django 4.2.17 on 2025-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_remove_games_judas_commander_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_map',
            field=models.ImageField(blank=True, null=True, upload_to='images/location_map', verbose_name='Карта проезда'),
        ),
    ]
