# Generated by Django 4.2.17 on 2025-05-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_location_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gpx',
            field=models.FileField(blank=True, null=True, upload_to='files/gpx', verbose_name='Файл *.gpx'),
        ),
        migrations.AddField(
            model_name='event',
            name='kml',
            field=models.FileField(blank=True, null=True, upload_to='files/kml', verbose_name='Файл *.kml'),
        ),
        migrations.AddField(
            model_name='event',
            name='kmz',
            field=models.FileField(blank=True, null=True, upload_to='files/kmz', verbose_name='Файл *.kmz'),
        ),
        migrations.AddField(
            model_name='games',
            name='gpx',
            field=models.FileField(blank=True, null=True, upload_to='files/gpx', verbose_name='Файл *.gpx'),
        ),
        migrations.AddField(
            model_name='games',
            name='kml',
            field=models.FileField(blank=True, null=True, upload_to='files/kml', verbose_name='Файл *.kml'),
        ),
        migrations.AddField(
            model_name='games',
            name='kmz',
            field=models.FileField(blank=True, null=True, upload_to='files/kmz', verbose_name='Файл *.kmz'),
        ),
        migrations.AlterField(
            model_name='gameeventnotification',
            name='message_for',
            field=models.SmallIntegerField(choices=[(1, 'В бот'), (2, 'В канал')], default=1, verbose_name='Сообщение для'),
        ),
    ]
